### ISSUE TITLE
Background step not working as expected with Scenario outline

### ISSUE THREAD

**Issue by harmin-parra** [behave/behave#1148]
The `backgroung` section is not taken into account by `behave`.
Modifications made to the `context` object in the `background` section, aren't persistent and aren't available for other steps.

The feature file:
```
Feature: online-store checkout

  As a user
  I want to shop online

  Background
    Given I am authenticated in the online store

  Scenario Outline: Calculator
    Given I have "<x>" products in my shopping cart
    When I add "<y>" products to my shopping cart
    Then I have "<total>" products in my shopping cart

    Examples:
        |  x  |  y | total |
        |  1  |  2 |  3    |
```
The steps implementations:
```
from behave import given, when, then
from mypackage.store import Cart

@given('I am authenticated in the online store')
def step_impl(context):
    context.cart = Cart()

@given('I have "{x}" products in my shopping cart')
def step_impl(context, x):
    context.cart.items = int(x)

@when('I add "{y}" products to my shopping cart')
def step_impl(context, y):
    context.cart.add_items(int(y))

@then('I have "{total}" products in my shopping cart')
def step_impl(context, total):
    assert context.cart.get_num_items() == int(total)
```

The shopping cart implementation:
```
class Cart(object):

    def __init__(self):
        self.items = 0

    def add_items(self, items):
        self.items += items

    def get_num_items(self):
        return self.items
```
When I execute `behave tests/behave/features/store.feature`

I get this result:
```
Feature: online-store checkout # tests/behave/features/store.feature:1
  As a user
  I want to shop online
  Background
  Given I am authenticated in the online store
  Scenario Outline: Calculator -- @1.1            # tests/behave/features/store.feature:16
    Given I have "1" products in my shopping cart # tests/behave/features/steps/steps_store.py:10 0.001s
      Traceback (most recent call last):
        File "/home/hpr/playwright/.venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/hpr/playwright/.venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "tests/behave/features/steps/steps_store.py", line 12, in step_impl
          context.cart.items = int(x)
          ^^^^^^^^^^^^
        File "/home/hpr/playwright/.venv/lib/python3.11/site-packages/behave/runner.py", line 321, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'cart'

    When I add "2" products to my shopping cart   # None
    Then I have "3" products in my shopping cart  # None
```

`context` isn't initialized with the code of the `background` section
The error messages says `AttributeError: 'Context' object has no attribute 'cart'`

I am using behave version 1.2.6

**Comment by harmin-parra** [comment]
**background** works fine with just **scenario** but not with **scenario outline**

**Comment by harmin-parra** [comment]
> ```
> Background
>     I am authenticated in the online store
> ```
> 
> If this is how you call the background step, this is wrong. You should add a keyword such as Given

I fixed the sample code and added the `Given` keyword.
It doesn't work either.

**Comment by harmin-parra** [comment]
**background** works fine just with **scenario** but not with **scenario outline**

**Comment by lu-maca** [comment]
@harmin-parra the syntax you are using is still wrong. You should add ":" after the keyword "Background".

**Comment by harmin-parra** [comment]
It works.

Thank you very much
