### ISSUE TITLE
Update Django Example to work with version >=1.7

### ISSUE THREAD

**Issue by mpetyx** [behave/behave#323]
Hello,
I was trying to create some tests for my django project, but it seems that the [script](https://github.com/behave/behave/blob/master/docs/django.rst) is deprecated for latest versions.

A fix was to remove the settings mechanism to the updated one,
Remove the existing lines,
```
from django.core.management import setup_environ
from myproject import settings
setup_environ(settings)
```
to,
```
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
from django.conf import settings
```

then replace the
`from django.core.handlers.wsgi import WSGIHandler`
with the
`from django.core.wsgi import get_wsgi_application`

and finally the error I get is,
```
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Any ideas?
Thank you very much in advance!
Michael

ps:
When we finalise this, I will create a pull request to update this.

**Comment by mixxorz** [comment]
Hi!

Check out [behave-django](https://pypi.python.org/pypi/behave-django/). It will make your life so much easier. As far as the docs go, I think they will be updated when the next version of behave comes out.

**Comment by mpetyx** [comment]
thanks a lot!
It seems like the solution I've been seeking for.

**Comment by mixxorz** [comment]
Hey.

While updating the docs for Django 1.7+, I came across the issue that `wsgi_intercept` doesn't have `mechanize` integration anymore.

I suggest we overhaul it to use something like [splinter](http://splinter.readthedocs.org/) for browser automation instead. What do you think?

**Comment by bittner** [comment]
Using behave with Django should all be much clearer [from the documentation](http://behave.readthedocs.org/en/latest/django.html) as soon as the docs online are updated to the state of the [`master` branch](https://github.com/behave/behave/blob/master/docs/django.rst). Merging PR #359 would also help quite a bit.

@jenisys Can we do this somehow? The last update of the documentation in RTD a quite some time ago, and some documentation bugs and outdated information has been fixed since then.

**Comment by bittner** [comment]
@jenisys Any chance [the (slightly out-dated) documentation](http://behave.readthedocs.org/en/latest/django.html) is updated from the [current master branch](https://github.com/behave/behave/blob/master/docs/django.rst) any time soon? This is quite overdue.  :frowning:

**Comment by jenisys** [comment]
@bittner, @mixxorz 
Can one of you look after this issue, thanks.

**Comment by bittner** [comment]
This should all work with the up-to-date documentation (i.e. the integration projects suggested in the yet-to-be-published docs).

 I'm tempted to suggest removing the code samples alltogether and only suggest the integrations. We'd have to maintain the code in here too, which I'd rather not do (there are no tests, think of it). Any strong opinions on that?

**Comment by bittner** [comment]
@jenisys I just noticed that the docs on [ReadTheDocs](http://readthedocs.org/projects/behave/) point to an [old repository of behave](https://github.com/jeamland/behave), which is **663 commits behind** [behave/behave]()'s `master` branch. [Triggering a build](http://readthedocs.org/projects/behave/builds/) doesn't change the docs online (naturally, because the sources are old). Interestingly, this is possible even without being owner or even logged in on RTD.

Can we fix that, and make it point to this repository? Who is [benno](https://readthedocs.org/profiles/benno/) on RTD, is this you, @jenisys?

**Comment by jenisys** [comment]
@bittner 
:smile: Yes, that is the old version from Benno (and forget to pass the access rights to me). See the page footer. Benno Rice and Richard Jones started the ``behave`` project (before handing it over to me). Therefore, we are using [python-behave](http://python-behave.readthedocs.org/en/latest/) in "ReadTheDocs" (as stated in [PROJECT_INFO.rst](https://github.com/behave/behave/blob/master/PROJECT_INFO.rst)).

Regarding the django page. I was initially thinking of providing a basic example in behave. But after the intro, we should probably point to the [usage page](https://pythonhosted.org/behave-django/usage.html) of ``behave-django`` docs.

Some of the syntax-highlighting code blocks does not seem to work. Are you sure that ``.. code:: python`` blocks work. I am normally using ``.. code-block:: python`` as stated by the [sphinx documentation](http://www.sphinx-doc.org/en/stable/markup/code.html).

**Comment by bittner** [comment]
That PR should do the trick. Now you just need to publish [the docs](http://pythonhosted.org/behave/django.html) after merging.

I'd also love to see @jeamland pass the RTD project over to you/us to allow us to do away with the confusion.

**Comment by bittner** [comment]
@jenisys Good news, you're an owner of the `behave` RTD account now! Not sure when this happened, but it looks like @jeamland [just added you there](http://readthedocs.org/projects/behave/) recently. :+1: (Thanks!)

You can now update the RTD project settings and add this repository as a dependency. -- It's really necessary to fix the confusion with the outdated + duplicate docs.

**Comment by jenisys** [comment]
@bittner I adjusted the RTD project "behave" to point to the Github repository now and triggered the build for latest and stable versions. I will decide later-on what will be done with the RTD "python-behave" project.

**Comment by bittner** [comment]
@jenisys That's cool. Can you please merge PR #429 and trigger the build for "latest" again, so that an up-to-date documentation for behave's Django integration is online?

I think we can safely close this issue afterwards.

**Comment by jeamland** [comment]
You should have rights on readthedocs now.

**Comment by jenisys** [comment]
@jeamland Thanks, I saw the comment about it from @bittner. I adjusted the settings to use the current behave repository.

**Comment by bittner** [comment]
I'd appreciate if we could merge PR #429 and close this issue. This is all fixed for quite a while.

**Comment by jenisys** [comment]
FIXED IN: behave-1.2.6.ev0

**Comment by bittner** [comment]
Thank you, Jens!

**Comment by bittner** [comment]
@jenisys This issue is only partially fixed (hence unresolved for more than a year), because we haven't managed to update the [behave docs on pythonhosted.org](http://pythonhosted.org/behave/django.html).

Interestingly, readthedocs.io hosts the [latest build of the docs](http://behave.readthedocs.io/en/latest/django.html) (probably due to automatically triggered builds). -- Ah, and I must admit I like the "old" design ([alabaster theme](https://pypi.python.org/pypi/alabaster)) still better...  :weary: 

**Can we upload the latest version** of the docs to pythonhosted.org, or alternatively redirect all traffic to RTD?

**Comment by jenisys** [comment]
https://pythonhosted.org/  docs are updated for each release only.
https://readthedocs.org/ can distinguish between the LATEST docs (representing the current state of the repository) and the last STABLE docs.
