### ISSUE TITLE
HTML Formatter encoding issue

### ISSUE THREAD

**Issue by messyhead** [behave/behave#380]
Hi. I'm using the HTML Formatter to generate reports when the tests are run in Jenkins. I'm getting a UnicodeEncodeError when it tries to encode a £ sign. I've narrowed this down to an issue with the html formatter, as when I use pretty format only, the error doesn't occur.

The error shown is;

UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3'

And it refers to line 225 in html.py.

I'm not a python developer though, so I'm having trouble fixing this.

**Comment by jenisys** [comment]
This should be solved by @vrutkovs in his [pull-request #60](https://github.com/behave/behave/pull/86) that provides the HTML formatter right now. As I can see, he has already provided help with problems in the past.

**Comment by vrutkovs** [comment]
Hey @messyhead, are you using the latest code from PR #60? Is the issue still happens there?

**Comment by messyhead** [comment]
I merged the latest code into my own fork with the latest behave master, and I'm using that.

**Comment by jenisys** [comment]
Should be resolved on special branch for HTML formatter.
